project:
  type: website

website:
  title: "Kylie's Portfolio"
  image: "Images/Icon_2025.png"
  favicon: "Images/Icon_2025.png"
  page-navigation: true
  navbar:
    logo: "Images/Icon_2025.png"
    title: false
    collapse-below: lg
    search: false
    pinned: true
    left: 
      - text: "Visual Analytics"
        menu: 
          - text: "Course Webpage"
            href: "https://akalestale.netlify.app/"
          - text: "Project PISA (Probing Influences on Singaporean Academia)"
            href: "https://projectpisa.netlify.app/"
          - text: "Project PISA (SHINY App)"
            href: "https://projectpisa.shinyapps.io/projectPISA/"
            
      - text: "Geospatial Analytics"
        menu: 
          - text: "Course Webpage"
            href: "https://wecouldgoanywhere.netlify.app/"
          - text: "Analysing Thailand Road Accidents (Singapore Geospatial Festival 2024)"
            href: "posters/ISSS626_BangkokAcc_Poster.png"
          - text: "Spatial Mobility Patterns in Singapore"
            href: "https://isss624-kytjy.netlify.app/"

            

      - text: "Others"
        menu: 
          - text: "Overseas Study Mission - Jakarta & Bandung"
            href: "posters/MGMT6070_OSM_Reflection_Poster.pdf"  

    right:
      - href: "https://www.linkedin.com/in/kylietjy/"
        text: "{{< fa brands linkedin size=lg >}}"
      - href: "https://github.com/kytjy/"
        text: "{{< fa brands github size=lg >}}"


format:
  html:
    grid:
      margin-width: 700px
    theme: 
      - theme.scss
    highlight-style: tango
    css: styles.css

editor: visual
